
# Url to access prometheus
prometheus:
  # Value is templated
  url: http://monitoring-kube-prometheus-prometheus.monitoring.svc
  port: 9090
  path: ""



rules:
  default: true
  custom:
  - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod: 
          resource: pod
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'

  resource:

    # cpu:
    #   containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}[3m])) by (<<.GroupBy>>)
    #   nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>) by (<<.GroupBy>>)
    #   resources:
    #     overrides:
    #       container_label_io_kubernetes_pod_namespace:
    #         resource: namespace
    #       node:
    #         resource: node
    #       container_label_io_kubernetes_pod_name:
    #         resource: pod
    #   containerLabel: container_label_io_kubernetes_container_name
    # memory:
    #   containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}) by (<<.GroupBy>>)
    #   nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
    #   resources:
    #     overrides:
    #       container_label_io_kubernetes_pod_namespace:
    #         resource: namespace
    #       node:
    #         resource: node
    #       container_label_io_kubernetes_pod_name:
    #         resource: pod
    #   containerLabel: container_label_io_kubernetes_container_name
    # window: 3m

    cpu:
      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}[3m])) by (<<.GroupBy>>)
      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
      resources:
        overrides:
          node:
            resource: node
          container_label_io_kubernetes_pod_namespace:
            resource: namespace
          container_label_io_kubernetes_pod_name:
            resource: pod
      containerLabel: container_label_io_kubernetes_container_name
    memory:
      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}) by (<<.GroupBy>>)
      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
      resources:
        overrides:
          node:
            resource: node
          container_label_io_kubernetes_pod_namespace:
            resource: namespace
          container_label_io_kubernetes_pod_name:
            resource: pod
      containerLabel: container_label_io_kubernetes_container_name
    window: 3m
