apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-jenkins
  namespace: jenkins
spec:
  storageClassName: efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi