---
commonLabels:
  prometheus: devops # if i dont set up this, the prometheus operator will ignore 

defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
  labels:
    app: prometheus
kubeEtcd:               # line 1057
  enabled: false
kubeScheduler: 
  enabled: false
kubeControllerManager: 
  enabled: false



# grafana:
#   adminPassword: prom-operator



## Deploy a Prometheus instance
##
prometheus:
  prometheusSpec:
    serviceMonitorSelector: 
      matchLabels: 
        prometheus: devops # this label will be used by prometheus operator to select monitor object


    ## Namespaces to be selected for ServiceMonitor discovery.
    ##
    serviceMonitorNamespaceSelector: 
      matchLabels:
        monitoring: prometheus

