---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-devopsbyexample-io
  namespace: cert-manager
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: blog.devopsbyexample.io
  dnsNames:
  - blog.shuhai.de
  - www.blog.shuhai.de
  secretName: blog-devopsbyexample-io-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: devopsbyexample-io-ca
    kind: Issuer
    group: cert-manager.io
    # namespace: cert-manager