---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs
provisioner: efs-storage
parameters:
  archiveOnDelete: "false"
  # run "id -G jenkins"
  # gidMin: "1000"
  # gidMax: "1000"
  # gidAllocate: "true"