# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-claim
#   namespace: jenkins
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-sc-1
#   resources:
#     requests:
#       storage: 8Gi


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jenkins
  name: efs-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi